import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

export const metadata: Metadata = {
    title: "Next Auth V5",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    // console.log(session);

    return (
        <SessionProvider session={session}>
            <html lang="en">
                <body>{children}</body>
            </html>
        </SessionProvider>
    );
}
